server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    url: jdbc:postgresql://localhost:5678/customer
    username: postgres
    password: 879470
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect